ResisDB:
  # IP: "122.116.102.141"
  # Port: 6380
  IP: "localhost"
  Port: 6379
  DB: 1

MysqlDB:
  # IP: "122.116.102.141"
  # Port: 3307
  IP: "127.0.0.1"
  Port: 3306
  DB: "demo"
  User: "demo"
  Password: "demo123"
  Network: "tcp"

GolangServer:
  IP: "localhost"
  Host: "0.0.0.0"
  Port: 8080
  ENV: "debug"
  ViewsPath: "server/view/html/*"

FlaskServer:
  IP: "localhost"
  Port: 5000