ResisDB:
  # IP: "redisserver"
  IP: "localhost"
  Port: 6379
  DB: 1

MysqlDB:
  # IP: "mysqlserver"
  IP: "localhost"
  Port: 3306
  DB: "demo"
  User: "demo"
  # Password: "~Demo123"
  Password: "demo123"
  Network: "tcp"

GolangServer:
  # IP: "golangserver"
  IP: "localhost"
  Port: 8080
  Host: "0.0.0.0"
  ENV: "debug"
  ViewsPath: "./internal/view/html/*"

FlaskServer:
  # IP: "flaskserver"
  IP: "localhost"
  Port: 5000
  SocketHost: "0.0.0.0"
  SocketPort: 5010