ResisDB:
  IP: "redisserver"
  Port: 6379
  DB: 1

MysqlDB:
  IP: "mysqlserver"
  Port: 3306
  DB: "demo"
  User: "demo"
  Password: "~Demo123"
  Network: "tcp"

GolangServer:
  IP: "golangserver"
  Port: 8080
  Host: "0.0.0.0"
  ENV: "debug"
  ViewsPath: "./internal/view/html/*"

FlaskServer:
  IP: "flaskserver"
  Port: 5000
  SocketHost: "0.0.0.0"
  SocketPort: 5010
